# -*- coding: utf-8 -*-
"""ConvertSdfToCsv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10IAY9QtxdFwz8uYBlOHGe8on0NYta_cO
"""

import pandas as pd
from rdkit import Chem

# Read the SDF file using RDKit
suppl = Chem.SDMolSupplier('gdb9.sdf')

# Convert the molecules to a pandas dataframe
data = []


# Convert the molecules to a pandas dataframe, skipping problematic molecules
for i, mol in enumerate(suppl):
    if mol is None:
        print(f'Could not read molecule at index {i}')
        continue
    try:
        smiles = Chem.MolToSmiles(mol)
        data.append({'SMILES': smiles})
    except ValueError as e:
        print(f'Could not convert molecule at index {i} to SMILES: {e}')

# Write the dataframe to a CSV file
df = pd.DataFrame(data)
df.to_csv('gdb9.sdf.csv', index=False)